const SITE = { email: 'hello@arceaus.com', book: 'https://cal.com/' };
const PROJECTS = [{"s": "ad-enterprise", "t": "AD-Enterprise", "c": "Enterprise", "y": "'22", "bg": "#d3d6e6", "img": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=75", "url": "https://ad-enterprise.framer.website", "d": "A website for an enterprise brand, designed and built by ARCEAUS."}, {"s": "nekro-ai", "t": "Nekro AI", "c": "AI Assistant", "y": "'26", "bg": "#dcdcc8", "img": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=75", "url": "https://nekro-site.vercel.app", "d": "A site and interface for an AI assistant product."}, {"s": "wrappdelights", "t": "Wrappdelights", "c": "B2B Bulk gifting", "y": "'26", "bg": "#c2b0b5", "img": "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1200&q=75", "url": "", "d": "A web presence for a B2B bulk gifting business."}, {"s": "monotone", "t": "Monotone", "c": "Figma Designs", "y": "'24", "bg": "#d9d3ea", "img": "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=75", "url": "", "d": "A set of Figma designs, from interface to prototype."}, {"s": "theblackrat", "t": "TheBlackRat", "c": "Creative Studio", "y": "'26", "bg": "#e3d0d2", "img": "https://images.unsplash.com/photo-1635776062127-d379bfcba9f8?auto=format&fit=crop&w=1200&q=75", "url": "", "d": "A website for a creative studio."}, {"s": "blackrat", "t": "Blackrat", "c": "Creative interactive", "y": "'23", "bg": "#cfd8d3", "img": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=75", "url": "", "d": "An interactive, creative web experience."}];
const PROJECT_MEDIA = {
  'ad-enterprise': ['projects/AD-enterprise/head.webp', 'projects/AD-enterprise/Screenshot%202026-09-27%20162958.webp', 'projects/AD-enterprise/Screenshot%202026-09-27%20163243.webp', 'projects/AD-enterprise/Screenshot%202026-09-27%20163316.webp', 'projects/AD-enterprise/Screenshot%202026-09-27%20163417.webp'],
  'blackrat': ['projects/Blackrat/head.webp', 'projects/Blackrat/Screenshot%202026-09-27%20171803.webp', 'projects/Blackrat/Screenshot%202026-09-27%20172445.webp'],
  'theblackrat': ['projects/Creative%20studio/head.webp', 'projects/Creative%20studio/Screenshot%202026-09-27%20171606.webp'],
  'monotone': ['projects/Monotone/head.webp', 'projects/Monotone/Screenshot%202026-09-27%20170705.webp'],
  'nekro-ai': ['projects/Nekro/head.webp', 'projects/Nekro/Screenshot%202026-09-27%20163627.webp', 'projects/Nekro/Screenshot%202026-09-27%20163828.webp', 'projects/Nekro/Screenshot%202026-09-27%20163909.webp', 'projects/Nekro/Screenshot%202026-09-27%20164013.webp'],
  'wrappdelights': ['projects/Wrappdelights/head.webp', 'projects/Wrappdelights/Screenshot%202026-09-27%20164140.webp', 'projects/Wrappdelights/Screenshot%202026-09-27%20170329.webp', 'projects/Wrappdelights/Screenshot%202026-09-27%20170406.webp', 'projects/Wrappdelights/Screenshot%202026-09-27%20170508.webp']
};
PROJECTS.forEach(project => { const media = PROJECT_MEDIA[project.s]; if (media) { project.img = media[0]; project.images = media; } });
const PRICING = [['Basic', '$200', 'For focused visual direction', ['Custom visual design', 'Responsive layouts', 'Design handoff']], ['Pro', '$500', 'For design and development', ['Complete visual design', 'Responsive development', 'Interaction and polish']], ['Complete', '$800', 'For a complete digital launch', ['Design and development', 'SEO and deployment', 'Creative direction']]];
const SERVICES = [["1. Brand Identity", "Creating distinctive visual identities that give your brand a clear and recognizable presence — from logos and typography to color systems and brand guidelines."], ["2. Web Design", "Designing refined, intuitive websites that balance visual impact, usability, and brand personality — from landing pages and portfolios to complete digital experiences."], ["3. Web Development", "Turning designs into fast, responsive, and reliable websites using modern technologies, with clean interactions and smooth performance across every device."], ["4. Creative Development", "Building digital experiences beyond standard websites — including interactive interfaces, animations, custom components, and immersive web experiences tailored to your brand."]];
const STACK = [["Framer", "No-code web design."], ["Figma", "UI/UX design & prototyping."], ["React", "Interactive front-end development."], ["Next.js", "Production-grade web applications."], ["GSAP", "Advanced animations & interactions."], ["Spline", "3D design"]];
const EXP = [["Freelance Digital Designer & Photographer", "France & International", "'13 - present", "Working with brands, agencies, and creatives to craft visual identities, design engaging websites, and capture photography that tells authentic stories. Projects range from brand launches to editorial campaigns."], ["Senior Digital Designer", "Creative Agency, Paris", "'16 - 2018", "Led design projects for lifestyle, fashion, and cultural brands. Oversaw concept development, UI/UX design, and visual direction while collaborating closely with copywriters, developers, and photographers."], ["Graphic Designer & Photographer", "Boutique Studio, Lyon", "'14 - 2016", "Created branding, print materials, and social media visuals for small to mid-sized businesses. Handled in-house photography for campaigns, products, and brand content."], ["Junior Designer", "Design Studio, Marseille", "'13 - 2014", "Assisted in the creation of brand assets, editorial layouts, and basic web designs. Supported senior designers and contributed to photography shoots, gaining hands-on experience in multidisciplinary creative work."]];
const FAQ = [["What services does ARCEAUS offer?", "Brand identity, web design, web development and creative development — from logos and design systems to fast, animated websites and custom interactive experiences."], ["Do you work with international clients?", "Yes. We're based in India and work with brands and teams around the world, with calls and updates handled online."], ["How does the project process work?", "We start with a call to understand your goals, then move through design, development and launch, sharing progress along the way."], ["Can you handle both design and development?", "Yes. Design and build happen in one team, so what is designed is what gets shipped."], ["How is your pricing determined?", "Pricing depends on scope, timeline and complexity. Book a call and we will share a clear quote."], ["Do you take on smaller or one-off projects?", "Yes. We take on one-off work such as a landing page or a brand refresh as well as larger builds."]];
(function () {
  const pages = [['index.html', 'Home'], ['about.html', 'Info'], ['work.html', 'Work'], ['contact.html', 'Contact']];
  const set = (id, h) => { const e = document.getElementById(id); if (e) e.outerHTML = h; };
  set('hdr', `<header><a class="logo" href="index.html"><img src="Assets/logo_full.svg" alt="ARCEAUS"></a><span class="clock" id="clk"></span><div class="hr"><a class="btn" href="${SITE.book}" target="_blank" rel="noopener"><i></i>Book a Call</a></div></header>`);
  const links = pages.map(p => `<a href="${p[0]}">${p[1]}</a>`).join('');
  set('ftr', document.body.hasAttribute('data-slim')
    ? `<footer class="slim pad"><small>© 2026 ARCEAUS</small><small><a href="mailto:${SITE.email}">${SITE.email}</a></small></footer>`
    : `<footer class="pad"><div class="logo"><img src="Assets/logo_full.svg" alt="ARCEAUS"></div><div>${links}</div><div class="f3">Available for work<br>Digital Designers<br>Based in India<br>Since 2026</div><a class="up" href="#top" aria-label="Back to top">↑</a><small>© 2026</small><small><a href="mailto:${SITE.email}">${SITE.email}</a></small><small>About Us.</small></footer>`);
  document.body.insertAdjacentHTML('beforeend', `<nav class="fl" aria-label="Pages">${links}</nav>`);
  const clk = document.getElementById('clk');
  const tick = () => { if (clk) clk.textContent = new Date().toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', timeZone: 'Asia/Kolkata' }); };
  tick(); setInterval(tick, 30000);
})();
